language: node_js
node_js: lts/*

addons:  
  chrome: stable

git:
  submodules: false

branches:
  only:
  - master

script:
  - travis_wait npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: deploy
  local-dir: dist
  on:
    branch: master

after_deploy:
  - npm install -g @lhci/cli
  - lhci autorun