language: node_js

git:
  submodules: false

branches:
  only:
  - master

install:
  - npm install

script:
  - travis_wait npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: deploy
  on:
    branch: master