---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: text
  name: titleShort
  label: Short Title
- type: datetime
  name: date
  label: Date
- type: file
  name: image
  label: Image
- type: textarea
  name: description
  label: Description
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- contents/projects/dissertation.md
- contents/projects/festimap.md
- contents/projects/hacksheffield.md
- contents/projects/hype.md
- contents/projects/icon-packs.md
- contents/projects/picnic-spots.md
- contents/projects/snapscroll.md
- contents/projects/stegaphoto.md
- contents/projects/tv-remote.md
- contents/projects/university-of-sheffield-brass-band.md
